### PR TITLE
Correction GetFirstDirectory

### PR DESCRIPTION
**Pull request by ykafia**
GetFirstDirectory should work with relative paths too and not remove omit the first character

### CODE REVIEW

**Comment by xoofx** [comment]
Thanks! Sorry, completely forgot about this PR.

Could you add some tests please?

**Comment by ykafia** [comment]
I've added some on a separate file as it's not internal to the UPath behavior, let me know if that's okay

**Comment by xoofx** [comment]
@ykafia many tests are failing in UPath likely due to the changes

**Comment by ykafia** [comment]
I will look into it

**Comment by ykafia** [comment]
All tests are passing now!

**Comment by xoofx** [comment]
Thanks!

**Pull request merged**
